profile:
  name: dev profile
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect : org.hibernate.dialect.PostgresPlusDialect
  datasource:
    url: jdbc:postgresql://db/postgres
    username: ridwan
    password: ridwan